name: price_radar
description: Price Radar

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_ai: ^3.2.0

  # Google
  google_sign_in: ^7.2.0

  # State Management
  provider: ^6.1.5+1

  # UI
  google_fonts: ^6.3.3
  flutter_svg: ^2.3.0
  flutter_spinkit: ^5.2.2

  # Storage
  shared_preferences: ^2.5.5

  # Scanner
  image_picker: ^1.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/animations/